course/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='course'
urlpatterns = [
    path('add/',views.add_user,name='add'),
    path('done/',views.done_page,name='done'),
    path('data/',views.data_page,name='data'),
    path('search/',views.search_page,name="search"),
    path('create/',views.create_page,name="create"),
    path('edit/',views.edit_page,name="edit"),

]

personalweb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('course/',include('course.urls',namespace='course')),


]

urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models

class TYP(models.Model):
    namecourse=models.CharField(max_length=50)
    def __str__(self):
        return self.namecourse

class COURSE(models.Model):
    code_name=models.IntegerField()
    nam=models.CharField(max_length=50)
    disc=models.TextField(default="")
    pic=models.ImageField(upload_to="course/images",default="")
    season=models.FileField(default="")
    cost=models.FloatField()
    namecourse=models.ForeignKey(TYP,on_delete=models.CASCADE,default="")


class Author(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=40)
    email=models.EmailField()

class Publisher(models.Model):
    name=models.CharField(max_length=30)
    address=models.CharField(max_length=50)
    city=models.CharField(max_length=60)
    state_province=models.CharField(max_length=30)
    country=models.CharField(max_length=50)
    website=models.URLField()


class Book(models.Model):
    title=models.CharField(max_length=100)
    authors=models.ManyToManyField(Author)
    publisher=models.ForeignKey(Publisher,on_delete=models.CASCADE)
    time_date=models.DateField()        

course/forms.py
from django import forms
from . import models


class CREATECOURSE(forms.ModelForm):

    class Meta:
        model=models.COURSE
        fields=['code_name','nam','disc','pic','season','cost','namecourse']

course/views.py
from django.shortcuts import render,redirect
from .forms import CREATECOURSE
from . import models

def add_user(request):
    form=CREATECOURSE()
    if(request.method=='POST'):
        form=CREATECOURSE(request.POST,request.FILES)
        if(form.is_valid()):
            print('yes its done')
            form.save()
            return redirect('course:data')

    return render(request,'course/add.html',{'form':form})


def done_page(request):
    return render(request,'course/after.html')

def data_page(request):
    delete_data=request.GET.get('delete-Text')
    get_data=models.COURSE.objects.filter(nam=delete_data).delete()
    data=models.COURSE.objects.all()
    return render(request,'course/data_page.html',{'data':data})


def search_page(request):
    data=request.GET.get('Text-search')
    search=models.COURSE.objects.filter(nam=data)
    x=list(search)
    if(len(x)==0):
        text='None Data'
        return render(request,'course/search_page.html',{'text':text})
    return render(request,'course/search_page.html',{'search':search})

def create_page(request):

    return render(request,'course/create_page.html')

def edit_page(request):
    data_update=request.GET.get('edit-data')
    data_update_text=request.GET.get('Update-Text')
    form=models.COURSE.objects.filter(nam=data_update).update(nam=data_update_text)
    data=models.COURSE.objects.all()
    return render(request,'course/data_page.html',{'data':data})

personalweb/views.py
from django.shortcuts import render


def home(request):

    return render(request,'home.html')

course/templates/course/add.html
<h1>Test add Page</h1>


<form action="{% url 'course:add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <br/>
    <input type="submit" value="Save"/>
</form>

course/templates/course/after.html
<h1> save is Done </h1>

course/templates/course/create_page.html
<h1>Create Page </h1>

course/templates/course/data_page.html
<h1>data page </h1>
<div dir="rtl">

  <form action="{% url 'course:search' %}">
    <span>نام دوره </span>
    <input type="text" name="Text-search" value="search field is CourseName"/>
    <input type="submit" value="Search"/>
  </form>

  <br/>



  <br/>
  <table border="1">
    <tr>
      <th>کد دوره</th>
      <th>نام دوره</th>
      <th>توضیحات</th>
      <th>لوگوی دوره</th>
      <th>سرفصل دوره</th>
      <th>هزینه</th>
      <th>نوع دوره</th>
    </tr>

  {% for item in data %}

    <tr>
      <td>{{item.code_name}}</td>
      <td>{{item.nam}}</td>
      <td>{{item.disc}}</td>
      <td><a href="{{item.pic.url}}">{{item.pic.url}}</a></td>
      <td><a href="{{item.season.url}}">{{item.season.url}}</a></td>
      <td>{{item.cost}}</td>
      <td>{{item.namecourse}}</td>
    </tr>
  {% endfor %}


  <br/>

  </table>
  <br/>
  <form action="{% url 'course:add' %}">
    <input type="submit" value="create"/>
  <form>


</div>

course/templates/course/search_page.html
<h1>search page </h1>
<head>
  <style>
    .search-input{
                 display:none;
                 }
  </style>
</head>
<h2>{{text}}</h2>



</form>

<form action="{% url 'course:data' %}">
  {% for i in search %}
    <input type="text" value="{{i.nam}}" class="search-input"  name="delete-Text"/>
  {% endfor %}
  <input type="submit" value="Delete Data"/>
  <br/>
  ..............................
</form>

<form action="{% url 'course:edit' %}">
    {% for j in search %}
       <input type="text" value="{{j.nam}}" class="search-input" name="edit-data"/>
    {% endfor %}
    <hr/>
    <input type="text" value="update ..."name="Update-Text"/>
    <br/>
    <input type="submit" value="Update"/>

</form>





<table border="1">
  {% for item in search %}

    <tr>

          <td>{{item.code_name}}</td>
          <td>{{item.nam}}</td>
          <td>{{item.disc}}</td>
          <td><a href="{{item.pic.url}}">{{item.pic.url}}</a></td>
          <td><a href="{{item.season.url}}">{{item.season.url}}</a></td>
          <td>{{item.cost}}</td>
          <td>{{item.namecourse}}</td>

    </tr>
  {% endfor %}
</table>

templates/home.html
<h1>This my Home Page</h1>